### ISSUE TITLE
Mod trying to load client class in dedicated server

### ISSUE THREAD

**Issue by itsdinkd** [Silverminer007/Shrines#26] opened 2021-12-18 03:22 UTC
Latest Shrines
Forge 39.0.5
MC 1.18.1

```java
03:16:58] [main/INFO]: Registering 20 structures of shrines Mod
failed to get walls all tags 
[03:16:58] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[03:16:58] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$3715/0x00000008015ddaa8@2e4d1066
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.5/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/balm@2.3.1+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.1-39.0.5/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.5/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/balm@2.3.1+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.1-39.0.5/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
failed to get walls all tags 
[03:16:58] [Thread-0/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[03:16:58] [Thread-0/ERROR]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        Index: 1
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$3715/0x00000008015ddaa8@5d44770d
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.5/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/balm@2.3.1+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.1-39.0.5/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.5/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@0.9.54/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at TRANSFORMER/balm@2.3.1+0/net.blay09.mods.balm.forge.config.ForgeBalmConfig.lambda$initializeBackingConfig$3(ForgeBalmConfig.java:149)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at LAYER PLUGIN/javafmllanguage@1.18.1-39.0.5/net.minecraftforge.fml.javafmlmod.FMLModContainer.lambda$new$0(FMLModContainer.java:55)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.lambda$dispatchConfigEvent$7(ModContainer.java:149)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.ModContainer.dispatchConfigEvent(ModContainer.java:149)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ModConfig.fireEvent(ModConfig.java:90)
        at LAYER PLUGIN/fmlcore@1.18.1-39.0.5/net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
        at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)

```

**Comment by Silverminer007** [comment] 2021-12-19 12:42
To fix this, I need to reproduce that crash. Just with a fresh forge installation and the shrines mod (version 3.0.0-beta2) nothing crashes and the server is starting. Have you used more mods with mine together? Is there a modpack to download them as package?

**Comment by itsdinkd** [comment] 2021-12-19 20:37
I'm building my own modpack ATM. I can send you the download if needed.
Just let me know and I can upload it for you.

**Comment by itsdinkd** [comment] 2021-12-19 20:37
Sorry. ATM as at the moment, not all the mods. Lol.

**Comment by Silverminer007** [comment] 2021-12-19 20:41
Download would be great. Hope that helps me to solve this

**Comment by red2blue** [comment] 2021-12-19 21:20
https://www72.zippyshare.com/v/n8CgXcBF/file.html please let me know when you downloaded so I can delete link. this is unfinished and I don't really want this out there yet.

**Comment by Silverminer007** [comment] 2021-12-26 12:18
Sorry, your download didn't work for me. Could you send me a new download link?

**Comment by Silverminer007** [comment] 2022-01-11 14:51
Fixed two bugs that are related to this one. Could you test if the issue still is up to date on beta 6?

**Comment by Silverminer007** [comment] 2022-02-14 12:41
I'll close this, because there haven't been any further activity. Feel free to reopen this issue or open a new one if this issue is still up to date

**Closed as completed by Silverminer007** 2022-02-14 12:41 UTC
Labels: bug, Version: 3.x.x
