### ISSUE TITLE
Server becomes unresponsive when loading certain chunks

### ISSUE THREAD

**Issue by Dysanix** [Silverminer007/Shrines#36] opened 2022-01-15 16:11 UTC
**Describe the bug**
Sometimes during world exploration, the server will become unresponsive and the server console will output the following:
```[15.01 10:52:26] [Server] [Server thread/INFO] [co.si.sh.ut.cu.ModTemplateManager/]: Constructing mod template manager with file: /shrines-saves```

There are times where it never seems to resolve automatically and we have to forcefully quit the server.
Last time that happened, the server crashed into:
```[15.01 11:17:04] [Server] [Server thread/ERROR] [minecraft/ChunkSerializer]: Unknown structure start: dungeons_enhanced:```
(Not sure if related)

Other times the server resolves within a couple of minutes and spammed this a couple times as it unfroze:
```[15.01 10:55:56] [Server] [Server thread/WARN] [structurize/]: Could not find iterator for value: using default instead!```
(Again: not sure if related)

**To Reproduce**
I am not sure how to reproduce this as it just suddenly started while playing Mineshafts and Monsters.
It happens when traveling / loading specific chunks.

**Expected behavior**
I would expect the chunk to load normally without causing the server to hang completely.

**Screenshots**
I have Spark logs instead, if that's useful.

This is profiled from everything being OK, to entering into such a chunk:
https://spark.lucko.me/uch1OB6WT6

This is profiled during the lag (the console is responsive, but the server is not, so I was able to execute the profile command):
https://spark.lucko.me/v3tqFAOV3T

And this is a profile of everything being normal, for comparison:
https://spark.lucko.me/NsrABzp20D

**Version (please complete the following information):**
 - OS: Windows/Java - Server on Bisecthosting
 - Forge Version 1.16.5
 - Mod Version 1.16.5

**Additional**
I also saw someone on CurseForge website mentioning a similar issue.
Hopefully with these Spark profiles provided, things will be easier to debug (if it is a bug).
In this case I think Lithium handles the whole chunk loading thing, so that's why that one is eating the most memory.
But I am very certain it is caused by Shrines somehow, as it's always accompanied with that /shrines-saves message.

**Comment by Silverminer007** [comment] 2022-01-15 17:28
I'm sorry to tell you, but I won't fix that bug for 1.8.1 (probably the version you're using), because I'm focusing on 2.0.0 (currently available trough Beta releases) where that bug is fixed. That has technical reason, as the bug is caused by a basic design issue of 1.8.1. Don't worry upgrading to 2.0.0 just because there are only Beta builds; these Beta build proved to be more stable than 1.8.1 in most cases. There is only one known issue with 2.0.0 which I've planned to fix before final release, but there should be no problem for you to upgrade

**Comment by Dysanix** [comment] 2022-01-15 18:03
> I'm sorry to tell you, but I won't fix that bug for 1.8.1 (probably the version you're using), because I'm focusing on 2.0.0 (currently available trough Beta releases) where that bug is fixed. That has technical reason, as the bug is caused by a basic design issue of 1.8.1. Don't worry upgrading to 2.0.0 just because there are only Beta builds; these Beta build proved to be more stable than 1.8.1 in most cases. There is only one known issue with 2.0.0 which I've planned to fix before final release, but there should be no problem for you to upgrade

Hi, I actually already tried upgrading to 2.0.0 by replacing the 1.8.1's jar with the 2.0.0 one.
Unfortunately upon joining, it spammed "structure not found" or something similar.
It seems as if all structures are no longer loaded or recognized with the new jar.

Did the folder structure change for 2.0.0, or how should I proceed?

**Comment by Silverminer007** [comment] 2022-01-15 18:10
Oh. I completely forgot that I've changed some structure's names. Sorry. First of all that message shouldn't be a problem and only appears the first time (I'm not sure if that's true for 1.16 too, I've only tried 1.18). I'm going to write a 'how-to-update' tutorial the next days. Thank you that you've reminded me! You should be able to change the structure's keys back to the old ones from 1.8.1 to completely prevent that issue, but I don't know all structure key changes from mind. Maybe I can change the mod to use the old keys when updating to 2.0.0 from 1.8.1. We'll see

**Comment by Silverminer007** [comment] 2022-01-15 18:31
I've created the update procedure and only need to test it. I'm going to do that tomorrow and then I'll make a new release that makes updating much easier

**Comment by Dysanix** [comment] 2022-01-16 12:56
> I've created the update procedure and only need to test it. I'm going to do that tomorrow and then I'll make a new release that makes updating much easier

Wow, Godspeed! That's really awesome of you! Can't wait to plop it into our server once it's finished.

**Comment by Silverminer007** [comment] 2022-01-16 16:50
Unfortunately it did not work as I had imagined, so you will have to wait another 1 - 2 days. I am sorry

**Comment by Silverminer007** [comment] 2022-01-17 16:11
I haven't had time to check it out yet, but in theory you should be able to update your server with this tutorial: https://github.com/Silverminer007/MinecraftModsUpdateChecker/blob/master/wiki/en_us/users/UpdateTo2.0.0From1.8.1.md
I recommend you to try this in another world first, and only if it works, you should try it on your server (but please **take a backup** anyway)

**Comment by Reio911** [comment] 2022-02-13 15:33
Not meaning to necro this, but is there a solution to this? I'm having the same issue (likely from the same modpack) but that link leads to a missing page.

**Comment by Silverminer007** [comment] 2022-02-13 19:16
1.8.1 isn't supported anymore. I'm sorry. The link doesn't work, because we have a new wiki. Here is the new link how to update: https://silverminer007.github.io/ShrinesWiki/wiki/en_us/users/UpdateTo2.0.0From1.8.1.html

If you use the recommended version (2.1.0+) you won't need to do anything when you update

**Comment by Reio911** [comment] 2022-02-13 20:06
Thanks! I did try that 2.1.0+ version and had a similar issue as stated above, where the console spams messages such as
[14:53:12] [Server thread/ERROR] [minecraft/ChunkSerializer]: Unknown structure start: shrines:flying_castle

~~followed by the server hanging and timing out.~~

**Comment by Silverminer007** [comment] 2022-02-13 20:49
Ok. Seems like the update of custom structures doesn't work. Could you open a new issue, as it isn't related to this one anymore?

**Comment by Silverminer007** [comment] 2022-02-14 12:44
I am closing this issue as 1.8.1 or lower will no longer receive support. Please upgrade to a newer version.
https://silverminer007.github.io/ShrinesWiki/wiki/en_us/users/UpdateTo2.0.0From1.8.1.html
or
https://silverminer007.github.io/ShrinesWiki/wiki/en_us/users/UpdateTo3.x.xFrom1.8.1.html

**Closed as completed by Silverminer007** 2022-02-14 12:44 UTC
Labels: bug, wontfix, Version: 1.x.x
