### ISSUE TITLE
Trader House infinitely long Locate command - server lockup

### ISSUE THREAD

**Issue by NighthowlerStudios** [Silverminer007/Shrines#16] opened 2021-07-25 11:03 UTC
On snapshot 2.0.0 Snapshot 7

using Kaleidio's Battle Pack 3.3.2

no logs usable, the server would just keep generating temporary chunks and never find it.

**Comment by Silverminer007** [comment] 2021-07-25 12:04
I've tried to reproduce (without the whole pack) and I'm unable to reproduce. I've tried with some changes done in the code so it's possible that I fixed that without knowing. Is the config still at default values? In which dimension did you try to locate the structure?
I've planned to upload a new snapshot later the day. Could you try if it's fixed there?

**Comment by Silverminer007** [comment] 2021-07-26 19:11
I'm going to close this now as the "bug" isn't really a bug. the problem was, that the distance between the structures was set to to low values, but the distance at needs to be at least between two structures was set to high which had prevented any structure to spawn

**Closed as completed by Silverminer007** 2021-07-26 19:11 UTC
Labels: bug
